import type { CardDefinition, DeckTemplate, HeroClassProfile } from "@dormstone/shared";

type CardInput = Omit<CardDefinition, "status" | "collectible" | "version" | "updatedAt" | "keywords" | "effects"> &
  Partial<Pick<CardDefinition, "collectible" | "keywords" | "effects" | "rules" | "sideboardSlots" | "deckRules" | "requiresTarget" | "choiceOptionCardIds" | "titanAbilityCardIds" | "forgeable">>;

const now = new Date().toISOString();

function card(input: CardInput): CardDefinition {
  return {
    ...input,
    status: "published",
    collectible: input.collectible ?? true,
    version: 1,
    updatedAt: now,
    keywords: input.keywords ?? [],
    effects: input.effects ?? []
  };
}

export const renathalPriestCards: CardDefinition[] = [
  card({ id: "reno_priest_raise_dead", name: "亡者复生", class: "priest", type: "spell", rarity: "common", cost: 0, text: "将本局对战中最后死亡的至多两个友方随从复制加入手牌。对你的英雄造成 3 点伤害。", rules: ["priest_raise_dead"] }),
  card({ id: "reno_priest_chameleos", name: "变色龙卡米洛斯", class: "priest", type: "minion", rarity: "legendary", cost: 1, attack: 1, health: 1, text: "如果这张牌在你的手牌中，每个回合都会变成你对手手牌中的一张牌。", races: ["BEAST"], rules: ["priest_chameleos"] }),
  card({ id: "reno_priest_nightshade_tea", name: "夜影花茶", class: "priest", type: "spell", rarity: "rare", cost: 1, text: "对一个随从造成 2 点伤害。对你的英雄造成 2 点伤害。可使用 3 次。", repeatableUses: 3, requiresTarget: true, effects: [{ type: "damage", amount: 2, target: "any_minion" }, { type: "damage", amount: 2, target: "own_hero" }] }),
  card({ id: "reno_priest_psychic_conjurer", name: "心灵咒术师", class: "priest", type: "minion", rarity: "common", cost: 1, attack: 1, health: 2, text: "战吼：复制对手牌库中的一张随机牌并置入你的手牌。", keywords: ["battlecry"], races: ["UNDEAD"], rules: ["priest_psychic_conjurer"] }),
  card({ id: "reno_priest_mend", name: "愈合", class: "priest", type: "spell", rarity: "common", cost: 1, text: "将一个随从恢复至生命值上限。抽一张牌。", requiresTarget: true, rules: ["priest_mend"] }),
  card({ id: "reno_priest_power_word_barrier", name: "真言术：障", class: "priest", type: "spell", rarity: "rare", cost: 1, text: "使一个角色获得圣盾。使你手牌中的随从牌获得 +2 生命值。", requiresTarget: true, rules: ["priest_power_word_barrier"] }),
  card({ id: "reno_priest_deafen", name: "致聋术", class: "priest", type: "spell", rarity: "common", cost: 1, text: "沉默一个随从。", effects: [{ type: "silence", target: "selected" }] }),
  card({ id: "reno_priest_papercraft_angel", name: "纸艺天使", class: "priest", type: "minion", rarity: "common", cost: 2, attack: 2, health: 3, text: "你的英雄技能的法力值消耗为 (0) 点。", rules: ["priest_papercraft_angel"] }),
  card({ id: "reno_priest_creation_protocol", name: "造物协议", class: "priest", type: "spell", rarity: "rare", cost: 2, text: "发现你牌库中一个随从的复制。锻造：再获取一张复制。", rules: ["priest_creation_protocol"], forgeable: true }),
  card({ id: "reno_priest_banker", name: "和善的银行职员", class: "priest", type: "minion", rarity: "epic", cost: 3, attack: 2, health: 4, text: "战吼：发现你牌库中的一张法术牌。快枪：改为从敌方牌库中发现。", keywords: ["battlecry"], races: ["WORGEN"], rules: ["priest_banker"] }),
  card({ id: "reno_priest_dirty_rat", name: "卑劣的脏鼠", class: "neutral", type: "minion", rarity: "epic", cost: 2, attack: 2, health: 6, text: "嘲讽。战吼：从对手手牌随机拉出一个随从。", keywords: ["taunt", "battlecry"], rules: ["dirty_rat"] }),
  card({ id: "reno_priest_kaldorei_spirit", name: "卡多雷精魂", class: "priest", type: "minion", rarity: "common", cost: 2, attack: 1, health: 3, text: "嘲讽，吸血。战吼：若你本回合使用过英雄技能，获得 +3/+3。", keywords: ["taunt", "lifesteal", "battlecry"], rules: ["priest_kaldorei_spirit"] }),
  card({ id: "reno_priest_thoughtsteal", name: "思维窃取", class: "priest", type: "spell", rarity: "common", cost: 2, text: "复制对手牌库中的两张牌并置入你的手牌。", rules: ["priest_thoughtsteal"] }),
  card({ id: "reno_priest_shadow_word_death", name: "暗言术：灭", class: "priest", type: "spell", rarity: "common", cost: 2, text: "消灭一个攻击力大于或等于 5 的随从。", requiresTarget: true, rules: ["priest_shadow_word_death"] }),
  card({ id: "reno_priest_power_chord_synchronize", name: "真弦术：合", class: "priest", type: "spell", rarity: "common", cost: 2, text: "选择一个随从，将一张它的复制置入你的手牌。终曲：使两者获得 +1/+2。", requiresTarget: true, rules: ["priest_power_chord_synchronize"] }),
  card({ id: "reno_priest_cozy_voljin", name: "惬意的沃金", class: "priest", type: "minion", rarity: "legendary", cost: 3, attack: 3, health: 3, text: "战吼：选择两个随从，交换其属性值。猎人游客。", keywords: ["battlecry"], requiresTarget: true, rules: ["priest_cozy_voljin"] }),
  card({ id: "reno_priest_lazul", name: "拉祖尔女士", class: "priest", type: "minion", rarity: "legendary", cost: 3, attack: 3, health: 2, text: "战吼：选择一张敌方手牌，复制并置入你的手牌。", keywords: ["battlecry"], rules: ["priest_lazul"] }),
  card({ id: "reno_priest_zola", name: "蛇发女妖佐拉", class: "neutral", type: "minion", rarity: "legendary", cost: 3, attack: 2, health: 2, text: "战吼：选择一个友方随从，将一张金色复制置入你的手牌。", keywords: ["battlecry"], requiresTarget: true, rules: ["priest_zola"] }),
  card({ id: "reno_priest_etc", name: "乐队经理精英牛头人酋长", class: "neutral", type: "minion", rarity: "legendary", cost: 4, attack: 4, health: 4, text: "构筑时带三张备牌。战吼：从尚未取出的乐队备牌中选择一张加入手牌。", keywords: ["battlecry"], sideboardSlots: 3, rules: ["etc_band_manager"] }),
  card({ id: "reno_priest_renathal", name: "雷纳索尔王子", class: "neutral", type: "minion", rarity: "legendary", cost: 3, attack: 3, health: 4, text: "对战开始时：你的起始牌库上限和起始生命值为 40。", deckRules: { deckSize: 40, startingHealth: 40 } }),
  card({ id: "reno_priest_twilight_torrent", name: "暮光洪流", class: "priest", type: "spell", rarity: "common", cost: 2, text: "选择一个角色。如果是友方角色，为其恢复 6 点生命值；如果是敌方角色，对其造成 3 点伤害。", requiresTarget: true, rules: ["priest_twilight_torrent"] }),
  card({ id: "reno_priest_nameless_one", name: "无名者", class: "priest", type: "minion", rarity: "legendary", cost: 4, attack: 4, health: 4, text: "战吼：选择一个随从。变形成为它的 4/4 复制，然后沉默该随从。", keywords: ["battlecry"], requiresTarget: true, rules: ["priest_nameless_one"] }),
  card({ id: "reno_priest_puppet_theatre", name: "木偶剧场", class: "priest", type: "location", rarity: "common", cost: 4, durability: 2, text: "选择一个敌方随从，获取它的 1/1 复制，其法力值消耗为 (1)。", requiresTarget: true, rules: ["priest_puppet_theatre"] }),
  card({ id: "reno_priest_glowstone_worm", name: "亮石旋岩虫", class: "priest", type: "minion", rarity: "rare", cost: 4, attack: 4, health: 4, text: "吸血。快枪：造成 5 点伤害。锻造：将快枪变为战吼。", keywords: ["lifesteal"], races: ["ELEMENTAL"], requiresTarget: true, rules: ["priest_glowstone_gyreworm"], forgeable: true }),
  card({ id: "reno_priest_mind_control_tech", name: "精神控制技师", class: "neutral", type: "minion", rarity: "rare", cost: 5, attack: 3, health: 3, text: "战吼：如果你的对手控制至少四个随从，随机获得其中一个的控制权。", keywords: ["battlecry"], rules: ["priest_mind_control_tech"] }),
  card({ id: "reno_priest_shadow_word_ruin", name: "暗言术：毁", class: "priest", type: "spell", rarity: "epic", cost: 4, text: "消灭所有攻击力大于或等于 5 的随从。", rules: ["priest_shadow_word_ruin"] }),
  card({ id: "reno_priest_repackage", name: "重新打包", class: "priest", type: "spell", rarity: "epic", cost: 7, text: "将所有随从塞进一个法力值消耗为 (2) 的箱子中，然后洗入对手的牌库。", rules: ["priest_repackage"] }),
  card({ id: "reno_priest_zilliax_deluxe_3000", name: "奇利亚斯豪华版3000型", class: "neutral", type: "minion", rarity: "legendary", cost: 9, attack: 6, health: 5, text: "复制模块 + 完美模块。战吼：召唤一个本随从的复制。圣盾，嘲讽，吸血，突袭。", keywords: ["battlecry", "divine_shield", "taunt", "lifesteal", "rush"], races: ["MECHANICAL"], rules: ["priest_zilliax_twin_perfect"] }),
  card({ id: "reno_priest_ignis", name: "永恒之火伊格尼斯", class: "neutral", type: "minion", rarity: "legendary", cost: 4, attack: 2, health: 4, text: "战吼：如果你在本局对战中锻造过一张牌，打造一把自定义武器。", keywords: ["battlecry"], rules: ["priest_ignis"] }),
  card({ id: "reno_priest_theotar", name: "疯狂公爵西塔尔", class: "neutral", type: "minion", rarity: "legendary", cost: 6, attack: 4, health: 4, text: "战吼：从双方手牌各选择一张牌并交换。", keywords: ["battlecry"], rules: ["theotar"] }),
  card({ id: "reno_priest_reno_jackson", name: "雷诺·杰克逊", class: "neutral", type: "minion", rarity: "legendary", cost: 6, attack: 4, health: 6, text: "战吼：若你的牌库没有重复牌，则将你的英雄恢复到生命上限。", keywords: ["battlecry"], rules: ["reno_jackson"] }),
  card({ id: "reno_priest_harmonic_pop", name: "悦耳流行歌", class: "priest", type: "spell", rarity: "rare", cost: 6, text: "对所有随从造成 3 点伤害。召唤一个 6/6 的流行歌星。（每回合切换。）", rules: ["priest_harmonic_pop"] }),
  card({ id: "reno_priest_lightbomb", name: "圣光炸弹", class: "priest", type: "spell", rarity: "epic", cost: 6, text: "对每个随从造成等同于其攻击力的伤害。", rules: ["priest_lightbomb"] }),
  card({ id: "reno_priest_elise_badlands", name: "荒地奇兵伊莉斯", class: "priest", type: "minion", rarity: "legendary", cost: 8, attack: 5, health: 5, text: "战吼：如果你的套牌开始时没有重复牌，随机召唤你牌库中四个随从的 5/5 复制。", keywords: ["battlecry"], rules: ["priest_elise_badlands"] }),
  card({ id: "reno_priest_marin_manager", name: "经理马林", class: "neutral", type: "minion", rarity: "legendary", cost: 7, attack: 6, health: 6, text: "海盗。战吼：选择一件奇妙的宝藏。将其他三件洗入你的牌库。", keywords: ["battlecry"], races: ["PIRATE"], rules: ["priest_marin_manager"] }),
  card({ id: "reno_priest_lone_ranger_reno", name: "孤胆游侠雷诺", class: "neutral", type: "hero", rarity: "legendary", cost: 8, text: "英雄牌。获得 5 点护甲。清理敌方战场。将你的英雄技能替换为每回合随机切换的雷诺手枪。", effects: [{ type: "gain_armor", amount: 5 }], rules: ["priest_lone_ranger_reno"] }),
  card({ id: "reno_priest_amanthul", name: "阿曼苏尔", class: "priest", type: "minion", rarity: "legendary", cost: 7, attack: 3, health: 10, text: "泰坦。在本随从使用一个技能后，发现任意职业的一张传说随从牌。", titanAbilityCardIds: ["reno_choice_amanthul_copy", "reno_choice_amanthul_exile", "reno_choice_amanthul_summon"], races: ["TITAN"] }),
  card({ id: "reno_priest_yogg_unleashed", name: "脱困古神尤格-萨隆", class: "neutral", type: "minion", rarity: "legendary", cost: 9, attack: 7, health: 5, text: "泰坦。在本随从使用一个技能后，施放两个随机法术。", titanAbilityCardIds: ["reno_choice_yogg_control", "reno_choice_yogg_tendrils", "reno_choice_yogg_madness"], races: ["OLD_GOD", "TITAN"], rules: ["priest_yogg_unleashed"] }),
  card({ id: "reno_priest_ceaseless_expanse", name: "无界空宇", class: "neutral", type: "minion", rarity: "legendary", cost: 100, attack: 10, health: 10, text: "每当抽牌，使用牌或有牌被摧毁时，本牌的法力值消耗减少 (1) 点。战吼：消灭所有其他随从。", keywords: ["battlecry"], rules: ["priest_ceaseless_expanse"] }),
  card({ id: "reno_priest_ysera_emerald", name: "伊瑟拉，翡翠守护巨龙", class: "neutral", type: "minion", rarity: "legendary", cost: 9, attack: 4, health: 12, text: "对战开始时：使双方玩家的法力水晶上限增加 5。战吼：获得 3 个法力水晶。", keywords: ["battlecry"], races: ["DRAGON"], rules: ["priest_ysera_emerald"] }),

  card({ id: "reno_choice_amanthul_copy", name: "阿曼苏尔：塑造星尘", class: "priest", type: "spell", rarity: "legendary", cost: 0, text: "选择一个非泰坦随从，召唤一个具有 +2/+2 的复制。", requiresTarget: true, rules: ["priest_amanthul_copy"], collectible: false }),
  card({ id: "reno_choice_amanthul_exile", name: "阿曼苏尔：扫出历史", class: "priest", type: "spell", rarity: "legendary", cost: 0, text: "选择两个敌方随从，将其移出对战。", requiresTarget: true, rules: ["priest_amanthul_exile"], collectible: false }),
  card({ id: "reno_choice_amanthul_summon", name: "阿曼苏尔：英雄视界", class: "priest", type: "spell", rarity: "legendary", cost: 0, text: "随机召唤一个法力值消耗为 (6) 的随从。使其获得嘲讽和吸血。", rules: ["priest_amanthul_summon"], collectible: false }),
  card({ id: "reno_choice_yogg_control", name: "尤格-萨隆：混乱统治", class: "neutral", type: "spell", rarity: "legendary", cost: 0, text: "获得一个敌方随从的控制权。", requiresTarget: true, rules: ["priest_yogg_control"], collectible: false }),
  card({ id: "reno_choice_yogg_tendrils", name: "尤格-萨隆：触须虫群", class: "neutral", type: "spell", rarity: "legendary", cost: 0, text: "用 1/1 的混乱触须填满你的手牌。", rules: ["priest_yogg_tendrils"], collectible: false }),
  card({ id: "reno_choice_yogg_madness", name: "尤格-萨隆：诱发狂乱", class: "neutral", type: "spell", rarity: "legendary", cost: 0, text: "使每个敌方随从随机攻击另一个敌方随从。", rules: ["priest_yogg_madness"], collectible: false }),
  card({ id: "reno_token_chaotic_tendril", name: "混乱触须", class: "neutral", type: "minion", rarity: "common", cost: 1, attack: 1, health: 1, text: "战吼：随机施放一个小法术。", keywords: ["battlecry"], collectible: false }),
  card({ id: "reno_token_repackaged_box", name: "重新打包的箱子", class: "neutral", type: "spell", rarity: "common", cost: 2, text: "将被塞进箱子里的随从置入你的手牌。", rules: ["priest_repackaged_box"], collectible: false }),
  card({ id: "reno_token_harmonic_popstar", name: "流行歌星", class: "neutral", type: "minion", rarity: "rare", cost: 6, attack: 6, health: 6, text: "悦耳流行歌召唤的流行歌星。", races: ["DRAENEI"], collectible: false }),
  card({ id: "reno_token_dissonant_popstar", name: "流行歌星", class: "neutral", type: "minion", rarity: "rare", cost: 3, attack: 3, health: 3, text: "刺耳流行歌召唤的流行歌星。", races: ["DRAENEI"], collectible: false }),
  card({ id: "reno_token_dissonant_pop", name: "刺耳流行歌", class: "priest", type: "spell", rarity: "rare", cost: 6, text: "对所有随从造成 6 点伤害。召唤一个 3/3 的流行歌星。（每回合切换。）", rules: ["priest_dissonant_pop"], collectible: false }),
  card({ id: "reno_token_ignis_weapon", name: "伊格尼斯的自定义武器", class: "neutral", type: "weapon", rarity: "legendary", cost: 5, attack: 4, durability: 4, text: "装备一把由伊格尼斯打造的自定义武器。", rules: ["priest_ignis_weapon"], collectible: false }),
  card({ id: "reno_token_ignis_weapon_battlecry", name: "伊格尼斯的自定义武器", class: "neutral", type: "weapon", rarity: "legendary", cost: 5, attack: 4, durability: 4, text: "装备一把由伊格尼斯打造的自定义武器。战吼：造成伤害。", requiresTarget: true, rules: ["priest_ignis_weapon"], collectible: false }),
  card({ id: "reno_choice_ignis_base_1", name: "伊格尼斯：小刀", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "打造 1 费 2/2 武器。", collectible: false }),
  card({ id: "reno_choice_ignis_base_5", name: "伊格尼斯：中刀", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "打造 5 费 3/4 武器。", collectible: false }),
  card({ id: "reno_choice_ignis_base_10", name: "伊格尼斯：大刀", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "打造 10 费 5/6 武器。", collectible: false }),
  card({ id: "reno_choice_ignis_trait_poisonous", name: "伊格尼斯：剧毒", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "武器获得剧毒。", collectible: false }),
  card({ id: "reno_choice_ignis_trait_lifesteal", name: "伊格尼斯：吸血", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "武器获得吸血。", collectible: false }),
  card({ id: "reno_choice_ignis_trait_windfury", name: "伊格尼斯：风怒", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "武器获得风怒。", collectible: false }),
  card({ id: "reno_choice_ignis_trait_adjacent", name: "伊格尼斯：攻击相邻", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "攻击时也会伤害相邻随从。", collectible: false }),
  card({ id: "reno_choice_ignis_trait_immune", name: "伊格尼斯：攻击免疫", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "你的英雄在攻击时免疫。", collectible: false }),
  card({ id: "reno_choice_ignis_special_summon", name: "伊格尼斯：米米尔隆的才华", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "攻击后召唤随机随从。", collectible: false }),
  card({ id: "reno_choice_ignis_special_damage", name: "伊格尼斯：尤顿的痛楚", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "战吼：造成伤害。", collectible: false }),
  card({ id: "reno_choice_ignis_special_draw", name: "伊格尼斯：弗蕾亚的智慧", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "攻击后抽牌。", collectible: false }),
  card({ id: "reno_choice_ignis_special_deathrattle", name: "伊格尼斯：霍迪尔之寒", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "亡语：对所有敌人造成伤害。", collectible: false }),
  card({ id: "reno_choice_ignis_special_armor", name: "伊格尼斯：提尔之光", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "攻击后获得护甲。", collectible: false }),
  card({ id: "reno_token_marin_wand", name: "奇妙魔杖", class: "neutral", type: "spell", rarity: "legendary", cost: 3, text: "抽三张牌，将其法力值消耗变为 (1) 点。", collectible: false }),
  card({ id: "reno_token_marin_crown", name: "扎罗格的王冠", class: "neutral", type: "spell", rarity: "legendary", cost: 3, text: "发现一张传说随从牌，召唤两个它的复制。", collectible: false }),
  card({ id: "reno_token_marin_goblet", name: "托林的酒杯", class: "neutral", type: "spell", rarity: "legendary", cost: 3, text: "抽一张牌，用它的复制填满你的手牌。", collectible: false }),
  card({ id: "reno_token_marin_kobold", name: "黄金狗头人", class: "neutral", type: "minion", rarity: "legendary", cost: 3, attack: 6, health: 6, text: "嘲讽。战吼：将你的手牌替换为法力值消耗减少 (1) 点的传说随从牌。", keywords: ["taunt", "battlecry"], collectible: false }),
  card({ id: "reno_token_fizzle_snapshot", name: "菲兹尔的快照", class: "neutral", type: "spell", rarity: "legendary", cost: 2, text: "将拍下快照时的手牌复制加入你的手牌。", rules: ["priest_fizzle_snapshot"], collectible: false }),
  card({ id: "reno_token_kiljaeden_demon", name: "燃烧军团恶魔", class: "neutral", type: "minion", rarity: "rare", cost: 4, attack: 4, health: 4, text: "基尔加丹的无尽恶魔。", races: ["DEMON"], collectible: false }),
  card({ id: "reno_token_kiljaeden_portal", name: "恶魔传送门", class: "neutral", type: "spell", rarity: "legendary", cost: 0, text: "回合开始时，从三个恶魔中选择一个加入手牌。传送门中的恶魔每回合永久获得 +2/+2。", collectible: false }),
  card({ id: "reno_portal_voidwalker", name: "虚空行者", class: "neutral", type: "minion", rarity: "common", cost: 1, attack: 1, health: 3, text: "嘲讽。", keywords: ["taunt"], races: ["DEMON"], collectible: false }),
  card({ id: "reno_portal_flame_imp", name: "烈焰小鬼", class: "neutral", type: "minion", rarity: "common", cost: 1, attack: 3, health: 2, text: "来自恶魔传送门的恶魔。", races: ["DEMON"], collectible: false }),
  card({ id: "reno_portal_succubus", name: "魅魔", class: "neutral", type: "minion", rarity: "common", cost: 2, attack: 4, health: 3, text: "来自恶魔传送门的恶魔。", races: ["DEMON"], collectible: false }),
  card({ id: "reno_portal_felguard", name: "恶魔卫士", class: "neutral", type: "minion", rarity: "rare", cost: 3, attack: 3, health: 5, text: "嘲讽。", keywords: ["taunt"], races: ["DEMON"], collectible: false }),
  card({ id: "reno_portal_voidcaller", name: "空灵召唤者", class: "neutral", type: "minion", rarity: "rare", cost: 4, attack: 3, health: 4, text: "亡语：召唤一个随机恶魔。", keywords: ["deathrattle"], races: ["DEMON"], collectible: false }),
  card({ id: "reno_portal_doomguard", name: "末日守卫", class: "neutral", type: "minion", rarity: "rare", cost: 5, attack: 5, health: 7, text: "冲锋。", keywords: ["charge"], races: ["DEMON"], collectible: false }),
  card({ id: "reno_portal_felsoul_jailer", name: "邪魂狱卒", class: "neutral", type: "minion", rarity: "rare", cost: 6, attack: 6, health: 6, text: "嘲讽。", keywords: ["taunt"], races: ["DEMON"], collectible: false }),
  card({ id: "reno_portal_abyssal_enforcer", name: "渊狱惩击者", class: "neutral", type: "minion", rarity: "epic", cost: 7, attack: 6, health: 6, text: "战吼：对所有其他角色造成 3 点伤害。", keywords: ["battlecry"], races: ["DEMON"], collectible: false }),
  card({ id: "reno_portal_illidari_inquisitor", name: "伊利达雷审判官", class: "neutral", type: "minion", rarity: "epic", cost: 8, attack: 8, health: 8, text: "突袭。", keywords: ["rush"], races: ["DEMON"], collectible: false }),
  card({ id: "reno_portal_malganis", name: "玛尔加尼斯", class: "neutral", type: "minion", rarity: "legendary", cost: 9, attack: 9, health: 7, text: "你的其他恶魔获得 +2/+2。", races: ["DEMON"], collectible: false }),
  card({ id: "reno_portal_lord_jaraxxus", name: "加拉克苏斯大王", class: "neutral", type: "minion", rarity: "legendary", cost: 9, attack: 8, health: 8, text: "恶魔传送门中的强大恶魔。", races: ["DEMON"], collectible: false }),
  card({ id: "reno_portal_archimonde", name: "阿克蒙德", class: "neutral", type: "minion", rarity: "legendary", cost: 10, attack: 10, health: 10, text: "嘲讽，吸血。", keywords: ["taunt", "lifesteal"], races: ["DEMON"], collectible: false }),
  card({ id: "reno_priest_dragonfire_potion", name: "龙息药水", class: "priest", type: "spell", rarity: "epic", cost: 5, text: "对所有非龙随从造成 5 点伤害。", rules: ["priest_dragonfire_potion"], collectible: false }),

  card({ id: "reno_band_photographer_fizzle", name: "摄影师菲兹尔", class: "neutral", type: "minion", rarity: "legendary", cost: 3, attack: 3, health: 3, text: "战吼：拍摄你当前手牌的快照并洗入你的牌库。每局对战限一次。", keywords: ["battlecry"], rules: ["priest_fizzle"] }),
  card({ id: "reno_band_kiljaeden", name: "基尔加丹", class: "neutral", type: "minion", rarity: "legendary", cost: 7, attack: 7, health: 7, text: "恶魔。战吼：将你的牌库替换为无尽的恶魔传送门。每个回合，恶魔获得额外 +2/+2。", keywords: ["battlecry"], races: ["DEMON"], rules: ["priest_kiljaeden"] }),
  card({ id: "reno_band_rustrot_viper", name: "锈烂蝰蛇", class: "neutral", type: "minion", rarity: "common", cost: 3, attack: 3, health: 4, text: "战吼：摧毁对手的武器。", keywords: ["battlecry"], rules: ["rustrot_viper"] }),
  card({ id: "reno_band_steamcleaner", name: "蒸汽清洁器", class: "neutral", type: "minion", rarity: "rare", cost: 5, attack: 5, health: 5, text: "战吼：摧毁双方牌库中所有非起始牌。", keywords: ["battlecry"], rules: ["steamcleaner"] }),

  // 旧版宇宙牧单卡仍保留在牌库中，避免既有测试和自定义卡组失效；它们不会进入新的预设前 40 张。
  card({ id: "reno_priest_finley", name: "海中向导芬利爵士", class: "neutral", type: "minion", rarity: "legendary", cost: 1, attack: 1, health: 3, text: "战吼：若你的牌库没有重复牌，交换你的手牌与牌库底部同等数量的牌。", keywords: ["battlecry"], rules: ["priest_finley"] }),
  card({ id: "reno_priest_zephrys", name: "了不起的杰弗里斯", class: "neutral", type: "minion", rarity: "legendary", cost: 2, attack: 3, health: 2, text: "战吼：若你的牌库没有重复牌，将一张应急愿望加入你的手牌。", keywords: ["battlecry"], rules: ["priest_zephrys"] }),
  card({ id: "reno_priest_fanboy", name: "饭圈迷弟", class: "priest", type: "minion", rarity: "common", cost: 2, attack: 2, health: 2, text: "抉择：使一个友方随从获得 +2 攻击力；或者获得 +2 生命值。", choiceOptionCardIds: ["reno_choice_fanboy_attack", "reno_choice_fanboy_health"] }),
  card({ id: "reno_priest_identity_theft", name: "盗用身份", class: "priest", type: "spell", rarity: "rare", cost: 3, text: "复制对手手牌中的一张随机牌和牌库中的一张随机牌并置入你的手牌。", rules: ["priest_identity_theft"] }),
  card({ id: "reno_priest_illucia", name: "裂心者伊露希亚", class: "priest", type: "minion", rarity: "legendary", cost: 3, attack: 3, health: 3, text: "战吼：交换双方手牌。", keywords: ["battlecry"], rules: ["priest_illucia"] }),
  card({ id: "reno_priest_tight_lipped", name: "锋鳞", class: "neutral", type: "minion", rarity: "epic", cost: 3, attack: 2, health: 4, text: "你的对手的卡牌法力值消耗不能少于 (2) 点。", rules: ["razorscale"] }),
  card({ id: "reno_priest_mixologist", name: "混调师", class: "neutral", type: "minion", rarity: "epic", cost: 3, attack: 2, health: 3, text: "战吼：将一份定制药水加入你的手牌。", keywords: ["battlecry"], rules: ["priest_mixologist"] }),
  card({ id: "reno_priest_hysteria", name: "狂乱", class: "priest", type: "spell", rarity: "epic", cost: 4, text: "选择一个随从。使其随机攻击其他随从，直到它死亡或场上没有其他随从。", requiresTarget: true, rules: ["priest_hysteria"] }),
  card({ id: "reno_priest_okani", name: "剑圣奥卡尼", class: "neutral", type: "minion", rarity: "legendary", cost: 4, attack: 2, health: 6, text: "抉择：反制对手打出的下一张随从牌；或者下一张法术牌。", keywords: ["battlecry"], choiceOptionCardIds: ["reno_choice_okani_minion", "reno_choice_okani_spell"] }),
  card({ id: "reno_priest_raza", name: "缚链者拉兹", class: "priest", type: "minion", rarity: "legendary", cost: 5, attack: 5, health: 5, text: "战吼：若你的牌库没有重复牌，本局对战你的英雄技能消耗变为 0。", keywords: ["battlecry"], rules: ["priest_raza"] }),
  card({ id: "reno_priest_magatha", name: "乐坛灾星玛加萨", class: "neutral", type: "minion", rarity: "legendary", cost: 5, attack: 5, health: 5, text: "战吼：抽五张牌。抽到的法术牌改为交给你的对手。", keywords: ["battlecry"], rules: ["priest_magatha"] }),
  card({ id: "reno_priest_miracle_salesman", name: "奇迹推销员", class: "neutral", type: "minion", rarity: "common", cost: 1, attack: 2, health: 2, text: "亡语：抽一张牌。", keywords: ["deathrattle"], effects: [{ type: "draw", amount: 1, trigger: "deathrattle" }] }),
  card({ id: "reno_priest_serena", name: "塞瑞娜·血羽", class: "priest", type: "minion", rarity: "legendary", cost: 2, attack: 1, health: 1, text: "战吼：选择一个敌方随从，偷取其攻击力和生命值，直到本随从拥有更多。", keywords: ["battlecry"], requiresTarget: true, rules: ["priest_serena"] }),
  card({ id: "reno_priest_cult_neophyte", name: "异教低阶牧师", class: "neutral", type: "minion", rarity: "rare", cost: 2, attack: 2, health: 3, text: "战吼：你对手下个回合的法术消耗增加 (1) 点。", keywords: ["battlecry"], rules: ["priest_cult_neophyte"] }),
  card({ id: "reno_priest_cathedral", name: "赎罪教堂", class: "priest", type: "spell", rarity: "rare", cost: 3, text: "使一个友方随从获得 +2/+1。抽一张牌。", requiresTarget: true, effects: [{ type: "buff", attack: 2, health: 1, target: "friendly_minion" }, { type: "draw", amount: 1 }] }),
  card({ id: "reno_priest_harvester", name: "嫉妒收割者", class: "priest", type: "minion", rarity: "legendary", cost: 3, attack: 4, health: 3, text: "战吼：复制对手手牌中的一张随机牌。", keywords: ["battlecry"], rules: ["priest_harvester"] }),
  card({ id: "reno_priest_holmes", name: "摩洛克·福尔摩斯", class: "neutral", type: "minion", rarity: "legendary", cost: 3, attack: 3, health: 4, text: "战吼：复制对手牌库中的两张随机牌。", keywords: ["battlecry"], rules: ["priest_holmes"] }),
  card({ id: "reno_priest_najark", name: "纳亚克·海克森", class: "priest", type: "minion", rarity: "legendary", cost: 4, attack: 1, health: 4, text: "战吼：夺取一个敌方随从。当纳亚克死亡时，将它归还。", keywords: ["battlecry", "deathrattle"], requiresTarget: true, rules: ["priest_najark"] }),
  card({ id: "reno_priest_loatheb", name: "洛欧塞布", class: "neutral", type: "minion", rarity: "legendary", cost: 5, attack: 5, health: 5, text: "战吼：你对手下个回合的法术消耗增加 (5) 点。", keywords: ["battlecry"], rules: ["priest_loatheb"] }),
  card({ id: "reno_priest_benedictus", name: "黑暗主教本尼迪塔斯", class: "priest", type: "minion", rarity: "legendary", cost: 5, attack: 5, health: 5, text: "对战开始时：将你的英雄技能替换为心灵尖刺。", rules: ["priest_benedictus"] }),
  card({ id: "reno_priest_spawn_of_shadows", name: "暗影子嗣", class: "priest", type: "minion", rarity: "epic", cost: 5, attack: 5, health: 5, text: "战吼：对双方英雄造成 4 点伤害。在场时，你使用英雄技能后再次如此。", keywords: ["battlecry"], rules: ["priest_spawn_of_shadows"] }),
  card({ id: "reno_priest_shadowreaper", name: "暗影收割者安度因", class: "priest", type: "spell", rarity: "legendary", cost: 8, text: "消灭所有攻击力大于或等于 5 的敌方随从。将你的英雄技能替换为虚空形态。", rules: ["priest_shadowreaper"] }),
  card({ id: "reno_priest_aviana", name: "艾维娜，艾露恩钦选者", class: "neutral", type: "minion", rarity: "legendary", cost: 9, attack: 5, health: 5, text: "战吼：在3个回合后，在本局对战中，你的卡牌的法力值消耗为（1）点。", keywords: ["battlecry"], rules: ["priest_aviana"] }),

  card({ id: "reno_choice_fanboy_attack", name: "饭圈迷弟：鼓动进攻", class: "priest", type: "spell", rarity: "common", cost: 0, text: "使一个友方随从获得 +2 攻击力。", requiresTarget: true, effects: [{ type: "buff", attack: 2, health: 0, target: "friendly_minion" }], collectible: false }),
  card({ id: "reno_choice_fanboy_health", name: "饭圈迷弟：保留体力", class: "priest", type: "spell", rarity: "common", cost: 0, text: "使一个友方随从获得 +2 生命值。", requiresTarget: true, effects: [{ type: "buff", attack: 0, health: 2, target: "friendly_minion" }], collectible: false }),
  card({ id: "reno_choice_okani_minion", name: "剑圣奥卡尼：反制随从", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "反制对手打出的下一张随从牌。", rules: ["priest_okani_minion"], collectible: false }),
  card({ id: "reno_choice_okani_spell", name: "剑圣奥卡尼：反制法术", class: "neutral", type: "spell", rarity: "common", cost: 0, text: "反制对手打出的下一张法术牌。", rules: ["priest_okani_spell"], collectible: false }),
  card({ id: "reno_choice_amanthul_remove", name: "阿曼苏尔：剥离", class: "priest", type: "spell", rarity: "legendary", cost: 0, text: "消灭一个敌方随从。", requiresTarget: true, effects: [{ type: "destroy", target: "enemy_minion" }], collectible: false }),
  card({ id: "reno_choice_amanthul_draw", name: "阿曼苏尔：远见", class: "priest", type: "spell", rarity: "legendary", cost: 0, text: "抽两张牌。", effects: [{ type: "draw", amount: 2 }], collectible: false }),
  card({ id: "reno_token_wish", name: "应急愿望", class: "priest", type: "spell", rarity: "rare", cost: 1, text: "造成 3 点伤害。抽一张牌。", effects: [{ type: "damage", amount: 3, target: "selected" }, { type: "draw", amount: 1 }], collectible: false }),
  card({ id: "reno_token_mixture", name: "定制药水", class: "neutral", type: "spell", rarity: "rare", cost: 1, text: "恢复 3 点生命值。抽一张牌。", effects: [{ type: "heal", amount: 3, target: "selected" }, { type: "draw", amount: 1 }], collectible: false }),
  card({ id: "hero_power_mind_spike", name: "心灵尖刺", class: "priest", type: "hero_power", rarity: "common", cost: 2, text: "造成 2 点伤害。", effects: [{ type: "damage", amount: 2, target: "selected", trigger: "hero_power" }], collectible: false }),
  card({ id: "hero_power_voidform", name: "虚空形态", class: "priest", type: "hero_power", rarity: "legendary", cost: 2, text: "造成 2 点伤害。", effects: [{ type: "damage", amount: 2, target: "selected", trigger: "hero_power" }], collectible: false }),
  card({ id: "hero_power_reno_bullet_arcane", name: "奥术子弹", class: "neutral", type: "hero_power", rarity: "legendary", cost: 2, text: "造成 2 点伤害。恢复 2 点本回合法力。", effects: [{ type: "damage", amount: 2, target: "selected", trigger: "hero_power" }, { type: "gain_mana", amount: 2, trigger: "hero_power" }], collectible: false }),
  card({ id: "hero_power_reno_bullet_fire", name: "火焰子弹", class: "neutral", type: "hero_power", rarity: "legendary", cost: 2, text: "造成 2 点伤害。对所有敌方随从造成 1 点伤害。", effects: [{ type: "damage", amount: 2, target: "selected", trigger: "hero_power" }, { type: "damage", amount: 1, target: "all_enemy_minions", trigger: "hero_power" }], collectible: false }),
  card({ id: "hero_power_reno_bullet_frost", name: "冰霜子弹", class: "neutral", type: "hero_power", rarity: "legendary", cost: 2, text: "造成 2 点伤害。获得 4 点护甲。", effects: [{ type: "damage", amount: 2, target: "selected", trigger: "hero_power" }, { type: "gain_armor", amount: 4, trigger: "hero_power" }], collectible: false }),
  card({ id: "hero_power_reno_bullet_holy", name: "神圣子弹", class: "neutral", type: "hero_power", rarity: "legendary", cost: 2, text: "造成 2 点伤害。随机使一个友方随从获得 +2/+2。", effects: [{ type: "damage", amount: 2, target: "selected", trigger: "hero_power" }], rules: ["priest_reno_holy_bullet"], collectible: false }),
  card({ id: "hero_power_reno_bullet_nature", name: "自然子弹", class: "neutral", type: "hero_power", rarity: "legendary", cost: 2, text: "造成 2 点伤害。发现一张法术牌。", effects: [{ type: "damage", amount: 2, target: "selected", trigger: "hero_power" }], rules: ["priest_reno_nature_bullet"], collectible: false }),
  card({ id: "hero_power_reno_bullet_shadow", name: "暗影子弹", class: "neutral", type: "hero_power", rarity: "legendary", cost: 2, text: "造成 2 点伤害。随机召唤一个 3 费随从。", effects: [{ type: "damage", amount: 2, target: "selected", trigger: "hero_power" }], rules: ["priest_reno_shadow_bullet"], collectible: false }),
  card({ id: "hero_power_reno_bullet_fel", name: "邪能子弹", class: "neutral", type: "hero_power", rarity: "legendary", cost: 2, text: "造成 2 点伤害。抽一张牌。", effects: [{ type: "damage", amount: 2, target: "selected", trigger: "hero_power" }, { type: "draw", amount: 1, trigger: "hero_power" }], collectible: false })
];

export const renathalPriestDeckCardIds = renathalPriestCards.slice(0, 40).map((item) => item.id);
export const renathalPriestSideboardCardIds = ["reno_priest_puppet_theatre", "reno_band_photographer_fizzle", "reno_band_kiljaeden"];

const sourceUrls = [
  "https://hearthstone.wiki.gg/wiki/Chameleos",
  "https://hearthstone.wiki.gg/wiki/Power_Word:_Barrier",
  "https://hearthstone.wiki.gg/wiki/Mend",
  "https://hearthstone.wiki.gg/wiki/Ysera,_Emerald_Aspect",
  "https://hearthstone.wiki.gg/wiki/The_Ceaseless_Expanse",
  "https://hearthstone.wiki.gg/wiki/Kil%27jaeden"
];

const priestHero: HeroClassProfile = {
  class: "priest",
  classZh: "牧师",
  classEn: "Priest",
  defaultHero: "安度因",
  heroPowerName: "次级治疗术",
  heroPowerCost: 2,
  heroPowerText: "恢复 2 点生命值。",
  traits: ["宇宙", "资源", "泰坦", "40 张雷纳索尔构筑"],
  sourceUrls
};

export const renathalPriestTemplate: DeckTemplate = {
  id: "custom_reno_priest_renathal",
  class: "priest",
  defaultClass: "priest",
  classZh: "牧师",
  classEn: "Priest",
  nameZh: "宇宙牧 / 雷纳索尔宇宙牧40",
  nameEn: "Renathal Highlander Priest",
  era: "用户截图预设",
  mode: "狂野",
  archetype: "宇宙控制",
  tags: ["宇宙", "雷纳索尔", "雷诺", "泰坦", "备牌"],
  fame: "S",
  annoyance: 5,
  uniqueness: 5,
  coreCardsZh: ["雷纳索尔王子", "雷诺·杰克逊", "阿曼苏尔", "脱困古神尤格-萨隆", "无界空宇", "伊瑟拉，翡翠守护巨龙"],
  coreCardsEn: ["Prince Renathal", "Reno Jackson", "Aman'Thul", "Yogg-Saron, Unleashed", "The Ceaseless Expanse", "Ysera, Emerald Aspect"],
  winCondition: "用宇宙体系和高质量解牌拖入后期，再依靠阿曼苏尔、尤格-萨隆、无界空宇和伊瑟拉争夺资源与场面。",
  whyIncluded: "按用户截图重建 40 张雷纳索尔宇宙牧，并将 E.T.C. 乐队改为木偶剧场、摄影师菲兹尔和基尔加丹。",
  recommendedUse: "直接在大厅选择这套预设开始对战。",
  sourceNote: "主套牌来自用户截图；单卡文本按 Hearthstone Wiki 与 HearthstoneJSON 当前资料建模，部分复杂机制映射到本项目现有操作流程。",
  sourceUrls,
  hero: priestHero,
  presetCardIds: renathalPriestDeckCardIds,
  sideboardCardIds: renathalPriestSideboardCardIds,
  expectedDeckSize: 40
};
